/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.13
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

type ApiKeyOut struct {
	ApiKey string `json:"apiKey,omitempty"`
	UserId string `json:"userId,omitempty"`
	Admin bool `json:"admin,omitempty"`
	Vetted bool `json:"vetted,omitempty"`
	Learnable bool `json:"learnable,omitempty"`
	Anonymized bool `json:"anonymized,omitempty"`
	Partner bool `json:"partner,omitempty"`
	Striped bool `json:"striped,omitempty"`
	Corporate bool `json:"corporate,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
}
