/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

type ApiUsageAggregatedOut struct {
	// Time unit is DAY, WEEK or MONTH depending on prior usage
	TimeUnit string `json:"timeUnit,omitempty"`
	// Start datetime of the reporting period
	PeriodStart int64 `json:"periodStart,omitempty"`
	// End datetime of the reporting period
	PeriodEnd int64 `json:"periodEnd,omitempty"`
	// Total usage in the current period
	TotalUsage int64 `json:"totalUsage,omitempty"`
	// If the history was truncaded due to data limit
	HistoryTruncated bool `json:"historyTruncated,omitempty"`
	// Data points : usage per DAY, WEEK or MONTH and per apiService
	Data [][]int32 `json:"data,omitempty"`
	// apiServices as column headers 
	ColHeaders []string `json:"colHeaders,omitempty"`
	// dates as row headers 
	RowHeaders []string `json:"rowHeaders,omitempty"`
}
