/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi
import (
	"time"
)

type InvoiceOut struct {
	Items []InvoiceItemOut `json:"items,omitempty"`
	UserId string `json:"userId,omitempty"`
	InvoiceId string `json:"invoiceId,omitempty"`
	IsStriped bool `json:"isStriped,omitempty"`
	StripeCustomerId string `json:"stripeCustomerId,omitempty"`
	AmountDue int64 `json:"amountDue,omitempty"`
	AmountPaid int64 `json:"amountPaid,omitempty"`
	AmountRemaining int64 `json:"amountRemaining,omitempty"`
	Attempted bool `json:"attempted,omitempty"`
	Currency string `json:"currency,omitempty"`
	InvoiceDate time.Time `json:"invoiceDate,omitempty"`
	DueDate time.Time `json:"dueDate,omitempty"`
	Description string `json:"description,omitempty"`
	InvoicePdf string `json:"invoicePdf,omitempty"`
	PeriodStart time.Time `json:"periodStart,omitempty"`
	PeriodEnd time.Time `json:"periodEnd,omitempty"`
	ReceiptNumber string `json:"receiptNumber,omitempty"`
	InvoiceStatus string `json:"invoiceStatus,omitempty"`
	SubTotal int64 `json:"subTotal,omitempty"`
	Tax int64 `json:"tax,omitempty"`
	TaxPercent int64 `json:"taxPercent,omitempty"`
	Total int64 `json:"total,omitempty"`
}
