/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiUsageAggregatedOut struct {
	TimeUnit string `json:"timeUnit,omitempty"`
	PeriodStart int64 `json:"periodStart,omitempty"`
	PeriodEnd int64 `json:"periodEnd,omitempty"`
	TotalUsage int64 `json:"totalUsage,omitempty"`
	HistoryTruncated bool `json:"historyTruncated,omitempty"`
	Data [][]int32 `json:"data,omitempty"`
	ColHeaders []string `json:"colHeaders,omitempty"`
	RowHeaders []string `json:"rowHeaders,omitempty"`
}
