/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

type SystemMetricsOut struct {
	CacheMetrics []CacheMetricsOut `json:"cacheMetrics,omitempty"`
	ClassifierMetrics []ClassifierMetricsOut `json:"classifierMetrics,omitempty"`
	SourceMetrics []SourceMetricsOut `json:"sourceMetrics,omitempty"`
	TotalMem int64 `json:"totalMem,omitempty"`
	FreeMem int64 `json:"freeMem,omitempty"`
	MaxMem int64 `json:"maxMem,omitempty"`
}
