/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// The current billing period.
type ApiBillingPeriodUsageOut struct {
	// User API Key.
	ApiKey string `json:"apiKey,omitempty"`
	// Datetime when the user subscribed to the plan.
	SubscriptionStarted int64 `json:"subscriptionStarted,omitempty"`
	// Datetime when the the plan's current period started.
	PeriodStarted int64 `json:"periodStarted,omitempty"`
	// Datetime when the the plan's current period endend.
	PeriodEnded int64 `json:"periodEnded,omitempty"`
	// Datetime when the the plan's current period endend (in Stripe). Internal and Stripe periodicity should ~coincide.
	StripeCurrentPeriodEnd int64 `json:"stripeCurrentPeriodEnd,omitempty"`
	// Datetime when the the plan's current period started (in Stripe). Internal and Stripe periodicity should ~coincide.
	StripeCurrentPeriodStart int64 `json:"stripeCurrentPeriodStart,omitempty"`
	// Current period billing status ex OPEN.
	BillingStatus string `json:"billingStatus,omitempty"`
	// Current period usage in units (NB some API endpoints use more than one unit).
	Usage int64 `json:"usage,omitempty"`
	// Current period soft limit (reaching the limit sends an email notification).
	SoftLimit int64 `json:"softLimit,omitempty"`
	// Current period hard limit (reaching the limit sends an email notification and blocks the API Key).
	HardLimit int64 `json:"hardLimit,omitempty"`
}
