/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Represents the output of inferring the LIKELY US 'race/ethnicity' from a personal name, given US country of residence and (optionally) a ZIP5 code.
type FirstLastNameUsRaceEthnicityOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	// The first name (also known as given name)
	FirstName string `json:"firstName,omitempty"`
	// The last name (also known as family name, or surname)
	LastName string `json:"lastName,omitempty"`
	// Second most likely US 'race'/ethnicity
	RaceEthnicityAlt string `json:"raceEthnicityAlt,omitempty"`
	// Most likely US 'race'/ethnicity
	RaceEthnicity string `json:"raceEthnicity,omitempty"`
	// Higher score is better, but score is not normalized. Use calibratedProbability if available. 
	Score float64 `json:"score,omitempty"`
	// List 'race'/ethnicities
	RaceEthnicitiesTop []string `json:"raceEthnicitiesTop,omitempty"`
	// The calibrated probability for raceEthnicity to have been guessed correctly.
	ProbabilityCalibrated float64 `json:"probabilityCalibrated,omitempty"`
	// The calibrated probability for raceEthnicity OR raceEthnicityAlt to have been guessed correctly.
	ProbabilityAltCalibrated float64 `json:"probabilityAltCalibrated,omitempty"`
}
