/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Represents the output of inferring the LIKELY ethnicity from a personal name, given an country of residence.
type FirstLastNameDiasporaedOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	// The first name (also known as given name)
	FirstName string `json:"firstName,omitempty"`
	// The last name (also known as family name, or surname)
	LastName string `json:"lastName,omitempty"`
	// Compatibility to NamSor_v1 Diaspora score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. 
	Score float64 `json:"score,omitempty"`
	// The second best alternative ethnicity
	EthnicityAlt string `json:"ethnicityAlt,omitempty"`
	// The most likely ethnicity
	Ethnicity string `json:"ethnicity,omitempty"`
	// Indicates if the output ethnicity is based on machine learning only, or further lifted as a known fact by a country-specific rule. Let us know if you believe ethnicity is incorrect on a specific case where lifted is true.
	Lifted bool `json:"lifted,omitempty"`
	// From input data, the countryIso2 of geographic context (US,CA etc.)
	CountryIso2 string `json:"countryIso2,omitempty"`
	// List most likely ethnicities (top 10)
	EthnicitiesTop []string `json:"ethnicitiesTop,omitempty"`
}
