/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Classified geo names
type PersonalNameGeoOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	// The input name.
	Name string `json:"name,omitempty"`
	// Higher score is better, but score is not normalized. Use calibratedProbability if available. 
	Score float64 `json:"score,omitempty"`
	// Most likely country 
	Country string `json:"country,omitempty"`
	// Second best alternative : country 
	CountryAlt string `json:"countryAlt,omitempty"`
	// Most likely region (based on country ISO2 code)
	Region string `json:"region,omitempty"`
	// Most likely top region (based on country ISO2 code)
	TopRegion string `json:"topRegion,omitempty"`
	// Most likely sub region (based on country ISO2 code)
	SubRegion string `json:"subRegion,omitempty"`
	// List countries (top 10)
	CountriesTop []string `json:"countriesTop,omitempty"`
	// The calibrated probability for country to have been guessed correctly.
	ProbabilityCalibrated float64 `json:"probabilityCalibrated,omitempty"`
	// The calibrated probability for country OR countryAlt to have been guessed correctly.
	ProbabilityAltCalibrated float64 `json:"probabilityAltCalibrated,omitempty"`
}
