/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

type ApiCounterV2Out struct {
	ApiKey ApiKeyOut `json:"apiKey,omitempty"`
	ApiService string `json:"apiService,omitempty"`
	CreatedDateTime int64 `json:"createdDateTime,omitempty"`
	TotalUsage int64 `json:"totalUsage,omitempty"`
	LastFlushedDateTime int64 `json:"lastFlushedDateTime,omitempty"`
	LastUsedDateTime int64 `json:"lastUsedDateTime,omitempty"`
	ServiceFeaturesUsage map[string]int64 `json:"serviceFeaturesUsage,omitempty"`
}
