/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Classified genderized names
type PersonalNameGenderedOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	// The input name
	Name string `json:"name,omitempty"`
	// Most likely gender
	LikelyGender string `json:"likelyGender,omitempty"`
	// Compatibility to NamSor_v1 Gender Scale M[-1..U..+1]F value
	GenderScale float64 `json:"genderScale,omitempty"`
	// Compatibility to NamSor_v1 Gender score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. 
	Score float64 `json:"score,omitempty"`
	// The calibrated probability for inferred gender to have been guessed correctly.
	ProbabilityCalibrated float64 `json:"probabilityCalibrated,omitempty"`
}
