/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Simple metrics on source, with details by classifier.
type SourceDetailedMetricsOut struct {
	ClassifierName string `json:"classifierName,omitempty"`
	Source ApiKeyOut `json:"source,omitempty"`
	AiEstimateTotal int64 `json:"aiEstimateTotal,omitempty"`
	AiEstimatePrecision float64 `json:"aiEstimatePrecision,omitempty"`
	AiEstimateRecall float64 `json:"aiEstimateRecall,omitempty"`
	MetricTimeStamp int64 `json:"metricTimeStamp,omitempty"`
	AiStartTime int64 `json:"aiStartTime,omitempty"`
	AiLearnTotal int64 `json:"aiLearnTotal,omitempty"`
	SnapshotDate int64 `json:"snapshotDate,omitempty"`
	ExpectedClassMetrics []ExpectedClassMetricsOut `json:"expectedClassMetrics,omitempty"`
}
