/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// The API Plan governing the subscription.
type ApiPlanSubscriptionOut struct {
	// User API Key.
	ApiKey string `json:"apiKey,omitempty"`
	// Datetime when the user subscribed to the current plan.
	PlanStarted int64 `json:"planStarted,omitempty"`
	// Datetime when the user subscribed to the prior plan.
	PriorPlanStarted int64 `json:"priorPlanStarted,omitempty"`
	// Datetime when the user ended the plan.
	PlanEnded int64 `json:"planEnded,omitempty"`
	// Applicable tax rate for the plan.
	TaxRate float64 `json:"taxRate,omitempty"`
	// Current plan name.
	PlanName string `json:"planName,omitempty"`
	// Current plan key (as in Stripe product).
	PlanBaseFeesKey string `json:"planBaseFeesKey,omitempty"`
	// Plan status.
	PlanStatus string `json:"planStatus,omitempty"`
	// Current plan quota in quantity of units (NB: some API use several units per name).
	PlanQuota int64 `json:"planQuota,omitempty"`
	// Current plan monthly price expressed in USD (includes a free quota).
	PriceUSD float64 `json:"priceUSD,omitempty"`
	// Current plan price for overages expressed in USD (extra price per unit above the free quota).
	PriceOverageUSD float64 `json:"priceOverageUSD,omitempty"`
	// Current plan price for overages expressed in Currency (extra price per unit above the free quota).
	Price float64 `json:"price,omitempty"`
	// Current plan price for overages expressed in Currency (extra price per unit above the free quota).
	PriceOverage float64 `json:"priceOverage,omitempty"`
	// Current plan Currency for prices.
	Currency string `json:"currency,omitempty"`
	// For USD, GBP, EUR - the factor is 1.
	CurrencyFactor float64 `json:"currencyFactor,omitempty"`
	// Stripe customer identifier.
	StripeCustomerId string `json:"stripeCustomerId,omitempty"`
	// Stripe status ex active.
	StripeStatus string `json:"stripeStatus,omitempty"`
	// Stripe subscription identifier.
	StripeSubscription string `json:"stripeSubscription,omitempty"`
	// Internal user identifier.
	UserId string `json:"userId,omitempty"`
}
