/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// The API Key.
type ApiKeyOut struct {
	// The user API Key.
	ApiKey string `json:"apiKey,omitempty"`
	// The user identifier.
	UserId string `json:"userId,omitempty"`
	// The API Key has admin role.
	Admin bool `json:"admin,omitempty"`
	// The API Key is vetted (assumed truthful) for machine learning.
	Vetted bool `json:"vetted,omitempty"`
	// The API Key is learnable (without assuming truthfulness) for machine learning. Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).
	Learnable bool `json:"learnable,omitempty"`
	// The API Key is anonymized (using SHA-252 digest for logging). Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).
	Anonymized bool `json:"anonymized,omitempty"`
	// The API Key has partner role.
	Partner bool `json:"partner,omitempty"`
	// The API Key is associated to a valid Stripe account.
	Striped bool `json:"striped,omitempty"`
	// The API Key has role corporate (ex SWIFT payments instead of Stripe payments).
	Corporate bool `json:"corporate,omitempty"`
	// The API Key is temporarily or permanently disabled.
	Disabled bool `json:"disabled,omitempty"`
}
