/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

type PersonalNameParsedOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	// The input name
	Name string `json:"name,omitempty"`
	// Name parsing is addressed as a classification problem, for example FN1LN1 means a first then last name order.
	NameParserType string `json:"nameParserType,omitempty"`
	// Second best alternative parsing. Name parsing is addressed as a classification problem, for example FN1LN1 means a first then last name order.
	NameParserTypeAlt string `json:"nameParserTypeAlt,omitempty"`
	FirstLastName FirstLastNameOut `json:"firstLastName,omitempty"`
	// Higher score is better, but score is not normalized. Use calibratedProbability if available. 
	Score float64 `json:"score,omitempty"`
}
