/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.15
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Represents the output of inferring the LIKELY country and phone code from a personal name and phone number.
type FirstLastNamePhoneCodedOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	// The first name (also known as given name)
	FirstName string `json:"firstName,omitempty"`
	// The last name (also known as family name, or surname)
	LastName string `json:"lastName,omitempty"`
	// The normalized phone number, verified using libphonenumber.
	InternationalPhoneNumberVerified string `json:"internationalPhoneNumberVerified,omitempty"`
	// The phone ISO2 country code, verified using libphonenumber.
	PhoneCountryIso2Verified string `json:"phoneCountryIso2Verified,omitempty"`
	// The phone country code of the phone number, verified using libphonenumber.
	PhoneCountryCode int32 `json:"phoneCountryCode,omitempty"`
	// The best alternative phone country code of the phone number.
	PhoneCountryCodeAlt int32 `json:"phoneCountryCodeAlt,omitempty"`
	// The likely country of the phone number.
	PhoneCountryIso2 string `json:"phoneCountryIso2,omitempty"`
	// The best alternative country of the phone number.
	PhoneCountryIso2Alt string `json:"phoneCountryIso2Alt,omitempty"`
	// The likely country of origin of the name.
	OriginCountryIso2 string `json:"originCountryIso2,omitempty"`
	// The best alternative country of origin of the name.
	OriginCountryIso2Alt string `json:"originCountryIso2Alt,omitempty"`
	// The input phone number.
	PhoneNumber string `json:"phoneNumber,omitempty"`
	// Indicates if the phone number could be positively verified using libphonenumber.
	Verified bool `json:"verified,omitempty"`
	// Higher score is better, but score is not normalized. Use calibratedProbability if available. 
	Score float64 `json:"score,omitempty"`
	CountryIso2 string `json:"countryIso2,omitempty"`
}
