/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.13
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package namsorapi

// Represents the output of inferring the LIKELY country and phone code from a personal name and phone number.
type FirstLastNamePhoneCodedOut struct {
	Script string `json:"script,omitempty"`
	Id string `json:"id,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	InternationalPhoneNumberVerified string `json:"internationalPhoneNumberVerified,omitempty"`
	PhoneCountryIso2Verified string `json:"phoneCountryIso2Verified,omitempty"`
	PhoneCountryCode int32 `json:"phoneCountryCode,omitempty"`
	PhoneCountryCodeAlt int32 `json:"phoneCountryCodeAlt,omitempty"`
	PhoneCountryIso2 string `json:"phoneCountryIso2,omitempty"`
	PhoneCountryIso2Alt string `json:"phoneCountryIso2Alt,omitempty"`
	OriginCountryIso2 string `json:"originCountryIso2,omitempty"`
	OriginCountryIso2Alt string `json:"originCountryIso2Alt,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	Verified bool `json:"verified,omitempty"`
	Score float64 `json:"score,omitempty"`
	CountryIso2 string `json:"countryIso2,omitempty"`
	Category string `json:"category,omitempty"`
}
