/*
 * NamSor API v2
 *
 * NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! 
 *
 * API version: 2.0.11
 * Contact: contact@namsor.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiPlanSubscriptionOut struct {
	ApiKey string `json:"apiKey,omitempty"`
	PlanStarted int64 `json:"planStarted,omitempty"`
	PriorPlanStarted int64 `json:"priorPlanStarted,omitempty"`
	PlanEnded int64 `json:"planEnded,omitempty"`
	TaxRate float64 `json:"taxRate,omitempty"`
	PlanName string `json:"planName,omitempty"`
	PlanBaseFeesKey string `json:"planBaseFeesKey,omitempty"`
	PlanStatus string `json:"planStatus,omitempty"`
	PlanQuota int64 `json:"planQuota,omitempty"`
	PriceUSD float64 `json:"priceUSD,omitempty"`
	PriceOverageUSD float64 `json:"priceOverageUSD,omitempty"`
	Price float64 `json:"price,omitempty"`
	PriceOverage float64 `json:"priceOverage,omitempty"`
	Currency string `json:"currency,omitempty"`
	CurrencyFactor float64 `json:"currencyFactor,omitempty"`
	StripeCustomerId string `json:"stripeCustomerId,omitempty"`
	StripeStatus string `json:"stripeStatus,omitempty"`
	StripeSubscription string `json:"stripeSubscription,omitempty"`
	UserId string `json:"userId,omitempty"`
}
